import { FirmwareConfig, Profile } from '../types';

function hexToRgb(hex: string): { r: number; g: number; b: number } {
  const clean = hex.replace('#', '');
  const num = parseInt(clean, 16);
  if (isNaN(num)) return { r: 0, g: 229, b: 255 };
  if (clean.length === 3) {
    const r = parseInt(clean[0] + clean[0], 16);
    const g = parseInt(clean[1] + clean[1], 16);
    const b = parseInt(clean[2] + clean[2], 16);
    return { r, g, b };
  }
  return {
    r: (num >> 16) & 255,
    g: (num >> 8) & 255,
    b: num & 255,
  };
}

export function generateEsp32Firmware(config: FirmwareConfig, profile: Profile): string {
  const isNativeUsb = config.chip === 'esp32_s2' || config.chip === 'esp32_s3';
  const isMpu6050 = config.sensorType === 'imu_mpu6050_spring' || config.sensorType === 'imu_mpu6050_joystick';
  const analogPinsStr = config.analogPins.join(', ');
  const buttonPinsStr = config.buttonPins.join(', ');

  const ledConfig = profile.ledRing || {
    brightness: 65,
    primaryColor: profile.ledColor || '#ff8800',
    secondaryColor: '#00e5ff',
    accentColor: '#ff3366',
    idleAnimation: 'breathing' as const,
    idleSpeed: 5,
    activeAnimation: 'rotational_twist_swirl' as const,
    activeSpeed: 6,
    individualLeds: Array(24).fill(profile.ledColor || '#ff8800'),
    ledCount: 24,
  };

  const powerConfig = profile.powerManagement || {
    batteryCapacityMah: 4200,
    enableLightSleep: true,
    lightSleepTimeoutMin: 15,
    lightSleepLedMode: 'dim_slow_breathe' as const,
    lightSleepCpuFreqMhz: 80,
    enableDeepSleep: true,
    deepSleepTimeoutMin: 60,
    wakeOnMotionThreshold: 15,
    wakeOnButtons: true,
    autoReconnectBle: true,
  };

  const pColor = hexToRgb(ledConfig.primaryColor);
  const sColor = hexToRgb(ledConfig.secondaryColor);
  const aColor = hexToRgb(ledConfig.accentColor);

  const customLedsArrayStr = (ledConfig.individualLeds || Array(24).fill(ledConfig.primaryColor))
    .slice(0, 24)
    .map((hex) => {
      const c = hexToRgb(hex);
      return `0x${((c.r << 16) | (c.g << 8) | c.b).toString(16).padStart(6, '0').toUpperCase()}`;
    })
    .join(', ');

  if (isMpu6050) {
    return `/**
 * =========================================================================
 * DIY 6-DOF SpaceMouse Embedded Firmware (MPU6050 Spring-Loaded Knob)
 * Target: ${config.chip.toUpperCase()} | Sensor: MPU-6050 (I2C)
 * Keypad: Treedix 9-Key Mechanical Matrix | Ring: 24x Adafruit NeoPixel
 * Power: 4200mAh LiPo + Multi-Tier Sleep Engine (Light Sleep & Hibernate)
 * Profile: ${profile.name} (${profile.targetApp})
 * Generated by DIY SpaceMouse Studio
 * =========================================================================
 */

#include <Arduino.h>
#include <Wire.h>
#include <Adafruit_MPU6050.h>
#include <Adafruit_Sensor.h>
#include <Adafruit_NeoPixel.h>
#include <Preferences.h>
#include <esp_sleep.h>
#include <esp_pm.h>
${config.firmwareMode === 'ble_gamepad_3d' ? `#include <BleGamepad.h>
BleGamepad bleGamepad("DIY SpaceMouse 6-DOF", "SpaceMouse Studio", 100);` : ''}

// --- HARDWARE PIN DEFINITIONS ---
#define SDA_PIN ${config.i2cSdaPin}  // Default ESP32 I2C SDA (GPIO 21)
#define SCL_PIN ${config.i2cSclPin}  // Default ESP32 I2C SCL (GPIO 22)
#define NEOPIXEL_PIN ${config.neopixelPin} // NeoPixel 24-LED Ring Data (GPIO 15)
#define NEOPIXEL_COUNT ${config.neopixelCount} // 24 LEDs

// Treedix 9-Key Mechanical Switch Pins (Direct to ESP32 with INPUT_PULLUP)
const uint8_t BUTTON_PINS[9] = { ${buttonPinsStr} };

// Hardware Objects
Adafruit_MPU6050 mpu;
Adafruit_NeoPixel strip(NEOPIXEL_COUNT, NEOPIXEL_PIN, NEO_GRB + NEO_KHZ800);
Preferences prefs;

// --- COLOR PALETTES & LED CONFIG ---
const uint8_t MASTER_BRIGHTNESS = ${Math.round((ledConfig.brightness / 100) * 255)};
const uint32_t COLOR_PRIMARY   = 0x${((pColor.r << 16) | (pColor.g << 8) | pColor.b).toString(16).padStart(6, '0').toUpperCase()};
const uint32_t COLOR_SECONDARY = 0x${((sColor.r << 16) | (sColor.g << 8) | sColor.b).toString(16).padStart(6, '0').toUpperCase()};
const uint32_t COLOR_ACCENT    = 0x${((aColor.r << 16) | (aColor.g << 8) | aColor.b).toString(16).padStart(6, '0').toUpperCase()};
const uint32_t CUSTOM_LEDS[24] = { ${customLedsArrayStr} };

// --- POWER MANAGEMENT TIMERS & THRESHOLDS ---
const uint32_t LIGHT_SLEEP_TIMEOUT_MS = ${powerConfig.lightSleepTimeoutMin} * 60 * 1000UL; // ${powerConfig.lightSleepTimeoutMin} minutes
const uint32_t DEEP_SLEEP_TIMEOUT_MS  = ${powerConfig.deepSleepTimeoutMin} * 60 * 1000UL;  // ${powerConfig.deepSleepTimeoutMin} minutes

enum DevicePowerState {
  STATE_ACTIVE = 0,
  STATE_LIGHT_SLEEP,
  STATE_DEEP_SLEEP
};

DevicePowerState currentPowerState = STATE_ACTIVE;
uint32_t lastInteractionTime = 0;

// --- KINEMATICS & FILTER VARIABLES ---
float gyroBiasX = 0, gyroBiasY = 0, gyroBiasZ = 0;
float accelBiasX = 0, accelBiasY = 0, accelBiasZ = 9.81;

// Complementary Filter State for Spring-Loaded Knob
float anglePitch = 0.0f; // Tilt Forward / Backward (Rx)
float angleRoll  = 0.0f; // Tilt Left / Right (Ry)
float angleYaw   = 0.0f; // Twist Left / Right (Rz)
float transX     = 0.0f; // Pan Left / Right (X)
float transY     = 0.0f; // Pan Forward / Back (Y)
float transZ     = 0.0f; // Zoom In / Out (Z)

// Filtered Output (-1.0 to +1.0)
float filtered6Dof[6] = { 0, 0, 0, 0, 0, 0 };

// Dynamic Parameters
struct SpaceMouseConfig {
  float deadzone[6] = { ${profile.axes.x.deadzone / 100}, ${profile.axes.y.deadzone / 100}, ${profile.axes.z.deadzone / 100}, ${profile.axes.rx.deadzone / 100}, ${profile.axes.ry.deadzone / 100}, ${profile.axes.rz.deadzone / 100} };
  float sensitivity[6] = { ${profile.axes.x.sensitivity}, ${profile.axes.y.sensitivity}, ${profile.axes.z.sensitivity}, ${profile.axes.rx.sensitivity}, ${profile.axes.ry.sensitivity}, ${profile.axes.rz.sensitivity} };
  bool inverted[6] = { ${profile.axes.x.inverted ? 'true' : 'false'}, ${profile.axes.y.inverted ? 'true' : 'false'}, ${profile.axes.z.inverted ? 'true' : 'false'}, ${profile.axes.rx.inverted ? 'true' : 'false'}, ${profile.axes.ry.inverted ? 'true' : 'false'}, ${profile.axes.rz.inverted ? 'true' : 'false'} };
  float smoothingAlpha = ${profile.filters.smoothingAlpha};
  bool lockPan = false;
  bool lockRotation = false;
  bool precisionMode = false;
} config;

uint32_t lastSampleTime = 0;
uint32_t lastLedUpdate = 0;
uint16_t lastButtonState = 0;
float ledHueAngle = 0.0f;

// Apply non-linear response curve (Expo / S-Curve)
float applyCurve(float input, float deadzone, float expoPower) {
  float absVal = fabs(input);
  if (absVal < deadzone) return 0.0f;
  float scaled = (absVal - deadzone) / (1.0f - deadzone);
  float curved = pow(scaled, expoPower);
  return (input < 0) ? -curved : curved;
}

// Helper to blend 2 RGB colors
uint32_t blendColor(uint32_t c1, uint32_t c2, float t) {
  t = constrain(t, 0.0f, 1.0f);
  uint8_t r1 = (c1 >> 16) & 0xFF, g1 = (c1 >> 8) & 0xFF, b1 = c1 & 0xFF;
  uint8_t r2 = (c2 >> 16) & 0xFF, g2 = (c2 >> 8) & 0xFF, b2 = c2 & 0xFF;
  uint8_t r = r1 + (r2 - r1) * t;
  uint8_t g = g1 + (g2 - g1) * t;
  uint8_t b = b1 + (b2 - b1) * t;
  return strip.Color(r, g, b);
}

// Helper to create rainbow hue
uint32_t colorWheel(uint8_t pos) {
  pos = 255 - pos;
  if (pos < 85) {
    return strip.Color(255 - pos * 3, 0, pos * 3);
  }
  if (pos < 170) {
    pos -= 85;
    return strip.Color(0, pos * 3, 255 - pos * 3);
  }
  pos -= 170;
  return strip.Color(pos * 3, 255 - pos * 3, 0);
}

// Tare / Center Calibrator
void calibrateZero() {
  float sumGx = 0, sumGy = 0, sumGz = 0;
  float sumAx = 0, sumAy = 0, sumAz = 0;
  const int samples = 200;

  // Flash LED purple during calibration
  for (int i = 0; i < NEOPIXEL_COUNT; i++) strip.setPixelColor(i, strip.Color(80, 0, 150));
  strip.show();

  for (int i = 0; i < samples; i++) {
    sensors_event_t a, g, temp;
    mpu.getEvent(&a, &g, &temp);
    sumGx += g.gyro.x;
    sumGy += g.gyro.y;
    sumGz += g.gyro.z;
    sumAx += a.acceleration.x;
    sumAy += a.acceleration.y;
    sumAz += a.acceleration.z;
    delay(3);
  }

  gyroBiasX = sumGx / samples;
  gyroBiasY = sumGy / samples;
  gyroBiasZ = sumGz / samples;
  accelBiasX = sumAx / samples;
  accelBiasY = sumAy / samples;
  accelBiasZ = sumAz / samples;

  anglePitch = 0.0f;
  angleRoll = 0.0f;
  angleYaw = 0.0f;
  transX = 0.0f;
  transY = 0.0f;
  transZ = 0.0f;

  lastInteractionTime = millis();
  Serial.println("$ACK,CAL_ZERO_MPU6050_COMPLETE");

  // Restore status LED
  for (int i = 0; i < NEOPIXEL_COUNT; i++) strip.setPixelColor(i, COLOR_PRIMARY);
  strip.show();
}

// NeoPixel 24-LED Ring Dual-State Engine (Idle vs In-Use Active)
void updateNeoPixelRing(float rx, float ry, float rz, float tx, float ty, float tz, bool inUse) {
  uint32_t now = millis();
  if (now - lastLedUpdate < 20) return; // 50 Hz Refresh
  lastLedUpdate = now;

  if (currentPowerState == STATE_LIGHT_SLEEP) {
    // Ultra-low power light sleep slow breathe (5% brightness)
    float breath = (sin(now * 0.001f) + 1.0f) * 0.5f * 0.08f + 0.02f;
    for (int i = 0; i < NEOPIXEL_COUNT; i++) {
      strip.setPixelColor(i, blendColor(0x000000, COLOR_PRIMARY, breath));
    }
    strip.show();
    return;
  }

  if (inUse) {
    // --- ACTIVE 6-DOF INTERACTION ANIMATION (${ledConfig.activeAnimation}) ---
    ${ledConfig.activeAnimation === 'rotational_twist_swirl' ? `
    // Rotational Twist Swirl follows physical knob Yaw
    ledHueAngle += (rz * 25.0f + 0.5f);
    int head = ((int)(ledHueAngle) % NEOPIXEL_COUNT + NEOPIXEL_COUNT) % NEOPIXEL_COUNT;
    for (int i = 0; i < NEOPIXEL_COUNT; i++) {
      int dist = abs(i - head);
      if (dist > NEOPIXEL_COUNT / 2) dist = NEOPIXEL_COUNT - dist;
      float intensity = max(0.15f, 1.0f - (float)dist / 5.0f);
      strip.setPixelColor(i, blendColor(COLOR_SECONDARY, COLOR_PRIMARY, intensity));
    }
    ` : ledConfig.activeAnimation === 'deflection_brightness' ? `
    // Deflection Flare focused in direction of tilt
    float forceAngle = atan2(ty, tx);
    for (int i = 0; i < NEOPIXEL_COUNT; i++) {
      float ledAngle = (i / 24.0f) * 6.28318f - 1.57079f;
      float diff = fabs(ledAngle - forceAngle);
      if (diff > 3.14159f) diff = 6.28318f - diff;
      float flare = pow(max(0.0f, 1.0f - diff / 3.14159f), 2.0f);
      strip.setPixelColor(i, blendColor(COLOR_SECONDARY, COLOR_ACCENT, flare));
    }
    ` : `
    // Dynamic Spectrum Pulse
    float totalMotion = fabs(rx) + fabs(ry) + fabs(rz) + fabs(tx) + fabs(ty) + fabs(tz);
    float pulse = (sin(now * 0.01f) + 1.0f) * 0.5f;
    for (int i = 0; i < NEOPIXEL_COUNT; i++) {
      strip.setPixelColor(i, blendColor(COLOR_PRIMARY, COLOR_ACCENT, pulse * totalMotion));
    }
    `}
  } else {
    // --- IDLE RESTING ANIMATION (${ledConfig.idleAnimation}) ---
    ${ledConfig.idleAnimation === 'spinning' ? `
    // Spinning Comet
    int cometHead = (now / (120 / ${ledConfig.idleSpeed})) % NEOPIXEL_COUNT;
    for (int i = 0; i < NEOPIXEL_COUNT; i++) {
      int dist = (i - cometHead + NEOPIXEL_COUNT) % NEOPIXEL_COUNT;
      float intensity = pow(max(0.0f, 1.0f - (float)dist / 12.0f), 2.5f);
      strip.setPixelColor(i, blendColor(0x000000, COLOR_PRIMARY, intensity));
    }
    ` : ledConfig.idleAnimation === 'two_halves_bouncing' ? `
    // Two Halves Bouncing / Ping-Pong
    float bounce = (sin(now * 0.003f * ${ledConfig.idleSpeed}) + 1.0f) * 0.5f;
    int pos1 = (int)(bounce * 11.0f);
    int pos2 = 23 - pos1;
    for (int i = 0; i < NEOPIXEL_COUNT; i++) {
      float intensity = (i == pos1 || i == pos2) ? 1.0f : 0.05f;
      strip.setPixelColor(i, blendColor(0x000000, (i == pos1 ? COLOR_PRIMARY : COLOR_ACCENT), intensity));
    }
    ` : ledConfig.idleAnimation === 'rainbow_cycle' ? `
    // Rainbow Cycle
    for (int i = 0; i < NEOPIXEL_COUNT; i++) {
      strip.setPixelColor(i, colorWheel(((i * 256 / NEOPIXEL_COUNT) + (now / 20)) & 255));
    }
    ` : ledConfig.idleAnimation === 'custom_per_led' ? `
    // Custom Per-LED Painted Pattern
    for (int i = 0; i < NEOPIXEL_COUNT; i++) {
      strip.setPixelColor(i, CUSTOM_LEDS[i]);
    }
    ` : `
    // Gentle Sinusoidal Breathing
    float breath = (sin(now * 0.002f * ${ledConfig.idleSpeed}) + 1.0f) * 0.5f * 0.7f + 0.3f;
    for (int i = 0; i < NEOPIXEL_COUNT; i++) {
      strip.setPixelColor(i, blendColor(COLOR_SECONDARY, COLOR_PRIMARY, breath));
    }
    `}
  }
  strip.show();
}

// Power Management State Machine (Active -> Light Sleep -> Deep Hibernate)
void handlePowerManagement(bool isInteracting) {
  uint32_t now = millis();

  if (isInteracting) {
    if (currentPowerState != STATE_ACTIVE) {
      // Wake back up to 240MHz instantly
      setCpuFrequencyMhz(240);
      strip.setBrightness(MASTER_BRIGHTNESS);
      currentPowerState = STATE_ACTIVE;
      Serial.println("$STATUS,WAKE_ACTIVE_240MHZ");
    }
    lastInteractionTime = now;
    return;
  }

  uint32_t idleDuration = now - lastInteractionTime;

  // 1. Check Light Sleep Trigger (${powerConfig.lightSleepTimeoutMin} minutes)
  ${powerConfig.enableLightSleep ? `
  if (idleDuration >= LIGHT_SLEEP_TIMEOUT_MS && idleDuration < DEEP_SLEEP_TIMEOUT_MS) {
    if (currentPowerState == STATE_ACTIVE) {
      currentPowerState = STATE_LIGHT_SLEEP;
      setCpuFrequencyMhz(${powerConfig.lightSleepCpuFreqMhz}); // Drop CPU clock to save battery
      strip.setBrightness(15); // Dim LEDs
      Serial.println("$STATUS,ENTERED_LIGHT_SLEEP_BLE_READY");
    }
  }
  ` : ''}

  // 2. Check Deep Sleep / Hibernate Trigger (${powerConfig.deepSleepTimeoutMin} minutes)
  ${powerConfig.enableDeepSleep ? `
  if (idleDuration >= DEEP_SLEEP_TIMEOUT_MS) {
    Serial.println("$STATUS,ENTERING_DEEP_SLEEP_HIBERNATE");
    // Turn off all 24 LEDs completely (0 mA)
    for (int i = 0; i < NEOPIXEL_COUNT; i++) strip.setPixelColor(i, 0);
    strip.show();
    strip.setBrightness(0);

    // Configure Button Interrupts for instant wakeup
    esp_sleep_enable_ext0_wakeup((gpio_num_t)BUTTON_PINS[8], 0); // Key 9 / Center button wakes
    esp_sleep_enable_ext1_wakeup(0x3F, ESP_EXT1_WAKEUP_ALL_LOW); // Any of buttons wakes

    // Enter Deep Sleep Hibernate
    esp_deep_sleep_start();
  }
  ` : ''}
}

void setup() {
  setCpuFrequencyMhz(240); // 240MHz high-speed boot
  Serial.begin(${config.baudRate});
  Wire.begin(SDA_PIN, SCL_PIN, 400000); // Fast 400kHz I2C

  // Init NeoPixel Ring
  strip.begin();
  strip.setBrightness(MASTER_BRIGHTNESS);
  strip.show();

  // Configure 9 Treedix Mechanical Buttons with internal pullups
  for (int i = 0; i < 9; i++) {
    pinMode(BUTTON_PINS[i], INPUT_PULLUP);
  }

  // Initialize MPU-6050
  if (!mpu.begin()) {
    Serial.println("$ERR,MPU6050_NOT_FOUND_CHECK_WIRING");
    for (int i = 0; i < NEOPIXEL_COUNT; i++) strip.setPixelColor(i, strip.Color(255, 0, 0));
    strip.show();
    while (1) { delay(500); }
  }

  // Configure MPU6050 ranges for spring-knob deflection
  mpu.setAccelerometerRange(MPU6050_RANGE_4_G);
  mpu.setGyroRange(MPU6050_RANGE_500_DEG);
  mpu.setFilterBandwidth(MPU6050_BAND_44_HZ);

  // Calibrate zero tare
  calibrateZero();

${config.firmwareMode === 'ble_gamepad_3d' ? `  bleGamepad.begin();
  Serial.println("$STATUS,BLE_GAMEPAD_STARTED");` : ''}

  lastInteractionTime = millis();
  Serial.println("$SM_STATUS,READY_MPU6050_SPRING,1.1.0");
}

void loop() {
  // 1. Process Serial Commands from Web Studio
  if (Serial.available()) {
    String cmd = Serial.readStringUntil('\\n');
    cmd.trim();
    if (cmd == "CAL_ZERO" || cmd == "TARE") {
      calibrateZero();
    } else if (cmd.startsWith("SET_BRIGHTNESS:")) {
      strip.setBrightness(cmd.substring(15).toInt());
      strip.show();
    }
  }

  // 2. Sensor Kinematics Loop
  uint32_t now = millis();
  float dt = (now - lastSampleTime) / 1000.0f;
  uint32_t loopRateHz = (currentPowerState == STATE_LIGHT_SLEEP) ? 25 : ${config.adcSamplingRateHz};

  if (dt >= (1.0f / loopRateHz)) {
    lastSampleTime = now;

    sensors_event_t a, g, temp;
    mpu.getEvent(&a, &g, &temp);

    // Remove Calibration Biases
    float ax = a.acceleration.x - accelBiasX;
    float ay = a.acceleration.y - accelBiasY;
    float az = a.acceleration.z; // Gravity vector
    float gx = (g.gyro.x - gyroBiasX) * 57.2958f; // deg/sec
    float gy = (g.gyro.y - gyroBiasY) * 57.2958f;
    float gz = (g.gyro.z - gyroBiasZ) * 57.2958f;

    // Pitch & Roll Calculation from Gravity Projection
    float pitchAccel = atan2(ay, sqrt(ax * ax + az * az)) * 57.2958f;
    float rollAccel  = atan2(-ax, az) * 57.2958f;

    // Complementary Filter: Gyro (94%) + Accelerometer (6%)
    const float alphaComp = 0.94f;
    anglePitch = alphaComp * (anglePitch + gx * dt) + (1.0f - alphaComp) * pitchAccel;
    angleRoll  = alphaComp * (angleRoll  + gy * dt) + (1.0f - alphaComp) * rollAccel;

    // Yaw Twist: Integrated Gyro with Spring Leaky Center Return
    angleYaw = (angleYaw + gz * dt) * 0.92f;

    // Translations: Spring Deflection Impulses
    transX = (transX * 0.85f) + (ax * 0.15f);
    transY = (transY * 0.85f) + (ay * 0.15f);
    transZ = (transZ * 0.85f) + ((az - accelBiasZ) * 0.15f);

    // Normalize to -1.0 .. +1.0
    float rawNorm[6];
    rawNorm[0] = constrain(transX / 3.0f, -1.0f, 1.0f);     // X (Pan Left/Right)
    rawNorm[1] = constrain(transY / 3.0f, -1.0f, 1.0f);     // Y (Pan Up/Down)
    rawNorm[2] = constrain(transZ / 4.0f, -1.0f, 1.0f);     // Z (Zoom)
    rawNorm[3] = constrain(anglePitch / 25.0f, -1.0f, 1.0f);// Rx (Tilt Pitch)
    rawNorm[4] = constrain(angleRoll  / 25.0f, -1.0f, 1.0f);// Ry (Tilt Roll)
    rawNorm[5] = constrain(angleYaw   / 30.0f, -1.0f, 1.0f);// Rz (Twist Yaw)

    // Apply Curves, Deadzones, Sensitivity, and Inversions
    for (int i = 0; i < 6; i++) {
      if (config.inverted[i]) rawNorm[i] = -rawNorm[i];
      float curved = applyCurve(rawNorm[i], config.deadzone[i], 1.8f);
      filtered6Dof[i] = (config.smoothingAlpha * curved) + ((1.0f - config.smoothingAlpha) * filtered6Dof[i]);
      filtered6Dof[i] *= config.sensitivity[i];
    }

    // Read 9 Treedix Mechanical Buttons
    uint16_t currentButtons = 0;
    for (int b = 0; b < 9; b++) {
      if (digitalRead(BUTTON_PINS[b]) == LOW) {
        currentButtons |= (1 << b);
      }
    }

    // Check interaction status (knob movement or button press)
    float totalDeflection = fabs(filtered6Dof[0]) + fabs(filtered6Dof[1]) + fabs(filtered6Dof[2]) + 
                            fabs(filtered6Dof[3]) + fabs(filtered6Dof[4]) + fabs(filtered6Dof[5]);
    bool isInteracting = (totalDeflection > 0.04f) || (currentButtons > 0);

    // Power Management State Check
    handlePowerManagement(isInteracting);

    // Button 9 (Key 9) Quick Hardware Tare
    if ((currentButtons & (1 << 8)) && !(lastButtonState & (1 << 8))) {
      calibrateZero();
    }

    // Update NeoPixel Lighting
    updateNeoPixelRing(filtered6Dof[3], filtered6Dof[4], filtered6Dof[5], filtered6Dof[0], filtered6Dof[1], filtered6Dof[2], isInteracting);

${config.firmwareMode === 'ble_gamepad_3d' ? `    // Send Bluetooth HID Gamepad Report
    if (bleGamepad.isConnected()) {
      int16_t bX = (int16_t)(filtered6Dof[0] * 32767);
      int16_t bY = (int16_t)(filtered6Dof[1] * 32767);
      int16_t bZ = (int16_t)(filtered6Dof[2] * 32767);
      int16_t bRx = (int16_t)(filtered6Dof[3] * 32767);
      int16_t bRy = (int16_t)(filtered6Dof[4] * 32767);
      int16_t bRz = (int16_t)(filtered6Dof[5] * 32767);
      bleGamepad.setAxes(bX, bY, bZ, bRz, bRx, bRy, 0, 0);
      for (int b = 0; b < 9; b++) {
        if (currentButtons & (1 << b)) bleGamepad.press(b + 1);
        else bleGamepad.release(b + 1);
      }
    }` : ''}

    // Output JSON Telemetry Packet to USB Serial
    Serial.printf("{\\"x\\":%.3f,\\"y\\":%.3f,\\"z\\":%.3f,\\"rx\\":%.3f,\\"ry\\":%.3f,\\"rz\\":%.3f,\\"adc\\":[%d,%d,%d,%d,%d,%d],\\"btns\\":%d}\\n",
      filtered6Dof[0], filtered6Dof[1], filtered6Dof[2], filtered6Dof[3], filtered6Dof[4], filtered6Dof[5],
      (int)(ax * 100), (int)(ay * 100), (int)(az * 100), (int)(gx * 10), (int)(gy * 10), (int)(gz * 10),
      currentButtons
    );

    lastButtonState = currentButtons;
  }
}
`;
  }

  return `/**
 * =========================================================================
 * DIY 6-DOF 3D SpaceMouse Embedded Firmware
 * Target: ${config.chip.toUpperCase()} | Mode: ${config.firmwareMode}
 * Generated by DIY SpaceMouse Studio
 * Profile: ${profile.name} (${profile.targetApp})
 * =========================================================================
 */

#include <Arduino.h>
#include <Preferences.h>

${isNativeUsb ? `// Native USB Multi-Axis Controller HID for ESP32-S2 / ESP32-S3
#include "USB.h"
#include "USBHID.h"

// 3Dconnexion standard Multi-Axis Controller HID Report Descriptor
static const uint8_t report_desc_spacemouse[] = {
  0x05, 0x01,        // Usage Page (Generic Desktop Ctrls)
  0x09, 0x08,        // Usage (Multi-axis Controller)
  0xA1, 0x01,        // Collection (Application)
  
  // Translation (X, Y, Z) - 16-bit signed
  0xA1, 0x00,        //   Collection (Physical)
  0x85, 0x01,        //     Report ID (1)
  0x09, 0x30,        //     Usage (X)
  0x09, 0x31,        //     Usage (Y)
  0x09, 0x32,        //     Usage (Z)
  0x16, 0x00, 0x80,  //     Logical Minimum (-32768)
  0x26, 0xFF, 0x7F,  //     Logical Maximum (32767)
  0x75, 0x10,        //     Report Size (16)
  0x95, 0x03,        //     Report Count (3)
  0x81, 0x02,        //     Input (Data,Var,Abs)
  0xC0,              //   End Collection
  
  // Rotation (Rx, Ry, Rz) - 16-bit signed
  0xA1, 0x00,        //   Collection (Physical)
  0x85, 0x02,        //     Report ID (2)
  0x09, 0x33,        //     Usage (Rx)
  0x09, 0x34,        //     Usage (Ry)
  0x09, 0x35,        //     Usage (Rz)
  0x16, 0x00, 0x80,  //     Logical Minimum (-32768)
  0x26, 0xFF, 0x7F,  //     Logical Maximum (32767)
  0x75, 0x10,        //     Report Size (16)
  0x95, 0x03,        //     Report Count (3)
  0x81, 0x02,        //     Input (Data,Var,Abs)
  0xC0,              //   End Collection

  // Buttons (Up to 16 buttons)
  0xA1, 0x00,        //   Collection (Physical)
  0x85, 0x03,        //     Report ID (3)
  0x05, 0x09,        //     Usage Page (Button)
  0x19, 0x01,        //     Usage Minimum (0x01)
  0x29, 0x10,        //     Usage Maximum (0x10)
  0x15, 0x00,        //     Logical Minimum (0)
  0x25, 0x01,        //     Logical Maximum (1)
  0x75, 0x01,        //     Report Size (1)
  0x95, 0x10,        //     Report Count (16)
  0x81, 0x02,        //     Input (Data,Var,Abs)
  0xC0,              //   End Collection

  0xC0               // End Collection
};

class SpaceMouseHID : public USBHIDDevice {
public:
  SpaceMouseHID() {
    static bool initialized = false;
    if (!initialized) {
      initialized = true;
      HID.addDevice(this, sizeof(report_desc_spacemouse));
    }
  }

  uint16_t _onGetDescriptor(uint8_t* dst) {
    memcpy(dst, report_desc_spacemouse, sizeof(report_desc_spacemouse));
    return sizeof(report_desc_spacemouse);
  }

  void begin() {
    HID.begin();
    USB.begin();
  }

  bool sendTranslation(int16_t x, int16_t y, int16_t z) {
    uint8_t report[7];
    report[0] = 0x01; // Report ID 1
    report[1] = x & 0xFF; report[2] = (x >> 8) & 0xFF;
    report[3] = y & 0xFF; report[4] = (y >> 8) & 0xFF;
    report[5] = z & 0xFF; report[6] = (z >> 8) & 0xFF;
    return HID.SendReport(1, report + 1, 6);
  }

  bool sendRotation(int16_t rx, int16_t ry, int16_t rz) {
    uint8_t report[7];
    report[0] = 0x02; // Report ID 2
    report[1] = rx & 0xFF; report[2] = (rx >> 8) & 0xFF;
    report[3] = ry & 0xFF; report[4] = (ry >> 8) & 0xFF;
    report[5] = rz & 0xFF; report[6] = (rz >> 8) & 0xFF;
    return HID.SendReport(2, report + 1, 6);
  }

  bool sendButtons(uint16_t buttonMask) {
    uint8_t report[3];
    report[0] = 0x03; // Report ID 3
    report[1] = buttonMask & 0xFF;
    report[2] = (buttonMask >> 8) & 0xFF;
    return HID.SendReport(3, report + 1, 2);
  }
};

SpaceMouseHID spacemouseHID;
` : `// Classic Serial & WebSerial Streaming Mode (ESP32-WROOM / C3 / Serial Bridge)`}

// --- HARDWARE PIN DEFINITIONS ---
const uint8_t ANALOG_PINS[6] = { ${analogPinsStr} }; // ADC Channels (SS49E Hall Sensors / Joysticks)
const uint8_t BUTTON_PINS[${config.buttonPins.length}] = { ${buttonPinsStr} }; // Tactile switch inputs
#define LED_PIN ${config.neopixelPin}
#define LED_COUNT ${config.neopixelCount}

// --- CALIBRATION & FILTER VARIABLES ---
Preferences prefs;
int rawZeros[6] = { 2048, 2048, 2048, 2048, 2048, 2048 };
float filteredOutput[6] = { 0, 0, 0, 0, 0, 0 };

// Dynamic Parameters (Synced via WebSerial Studio)
struct SpaceMouseConfig {
  float deadzone[6] = { ${profile.axes.x.deadzone / 100}, ${profile.axes.y.deadzone / 100}, ${profile.axes.z.deadzone / 100}, ${profile.axes.rx.deadzone / 100}, ${profile.axes.ry.deadzone / 100}, ${profile.axes.rz.deadzone / 100} };
  float sensitivity[6] = { ${profile.axes.x.sensitivity}, ${profile.axes.y.sensitivity}, ${profile.axes.z.sensitivity}, ${profile.axes.rx.sensitivity}, ${profile.axes.ry.sensitivity}, ${profile.axes.rz.sensitivity} };
  bool inverted[6] = { ${profile.axes.x.inverted ? 'true' : 'false'}, ${profile.axes.y.inverted ? 'true' : 'false'}, ${profile.axes.z.inverted ? 'true' : 'false'}, ${profile.axes.rx.inverted ? 'true' : 'false'}, ${profile.axes.ry.inverted ? 'true' : 'false'}, ${profile.axes.rz.inverted ? 'true' : 'false'} };
  float smoothingAlpha = ${profile.filters.smoothingAlpha};
  bool lockPan = false;
  bool lockRotation = false;
  bool precisionMode = false;
} config;

uint32_t lastSampleTime = 0;
uint16_t lastButtonState = 0;

// Apply non-linear response curve (Expo / S-Curve)
float applyCurve(float input, float deadzone, float expoPower) {
  float absVal = fabs(input);
  if (absVal < deadzone) return 0.0f;
  
  // Rescale range beyond deadzone from 0.0 to 1.0
  float scaled = (absVal - deadzone) / (1.0f - deadzone);
  float curved = pow(scaled, expoPower);
  return (input < 0) ? -curved : curved;
}

// Tare / Center Calibrator
void calibrateZero() {
  long sums[6] = {0};
  const int samples = 200;
  for (int i = 0; i < samples; i++) {
    for (int ch = 0; ch < 6; ch++) {
      sums[ch] += analogRead(ANALOG_PINS[ch]);
    }
    delay(2);
  }
  for (int ch = 0; ch < 6; ch++) {
    rawZeros[ch] = sums[ch] / samples;
  }
  
  // Save to ESP32 Flash NVS
  prefs.begin("spacemouse", false);
  prefs.putBytes("zeros", rawZeros, sizeof(rawZeros));
  prefs.end();
  
  Serial.printf("$ACK,CAL_ZERO,%d,%d,%d,%d,%d,%d\\n", rawZeros[0], rawZeros[1], rawZeros[2], rawZeros[3], rawZeros[4], rawZeros[5]);
}

void setup() {
  Serial.begin(${config.baudRate});
  analogReadResolution(12); // 12-bit ADC (0-4095)

  // Configure Button Pins with Internal Pullups
  for (int i = 0; i < ${config.buttonPins.length}; i++) {
    pinMode(BUTTON_PINS[i], INPUT_PULLUP);
  }

  // Load Calibration from NVS
  prefs.begin("spacemouse", true);
  if (prefs.isKey("zeros")) {
    prefs.getBytes("zeros", rawZeros, sizeof(rawZeros));
  } else {
    // If first boot, calibrate zero tare automatically
    calibrateZero();
  }
  prefs.end();

${isNativeUsb ? '  spacemouseHID.begin();' : ''}
  Serial.println("$SM_STATUS,READY,1.0.0");
}

void loop() {
  // 1. Process Incoming Serial Commands from Web Configurator
  if (Serial.available()) {
    String cmd = Serial.readStringUntil('\\n');
    cmd.trim();
    if (cmd == "CAL_ZERO") {
      calibrateZero();
    } else if (cmd == "GET_CONFIG") {
      Serial.printf("{\\"alpha\\":%.2f,\\"zeros\\":[%d,%d,%d,%d,%d,%d]}\\n", 
        config.smoothingAlpha, rawZeros[0], rawZeros[1], rawZeros[2], rawZeros[3], rawZeros[4], rawZeros[5]);
    } else if (cmd.startsWith("SET_ALPHA:")) {
      config.smoothingAlpha = cmd.substring(10).toFloat();
      Serial.println("$ACK,ALPHA_SET");
    }
  }

  // 2. Sample Sensors at Target Rate (${config.adcSamplingRateHz} Hz)
  uint32_t now = millis();
  if (now - lastSampleTime >= (1000 / ${config.adcSamplingRateHz})) {
    lastSampleTime = now;

    // Read 6 ADC Channels
    float normalized[6];
    int rawReadings[6];
    for (int ch = 0; ch < 6; ch++) {
      rawReadings[ch] = analogRead(ANALOG_PINS[ch]);
      // Normalize to -1.0 .. +1.0 relative to center tare
      float diff = (float)(rawReadings[ch] - rawZeros[ch]);
      float norm = diff / 1800.0f; // Typical SS49E max deflection span
      if (norm > 1.0f) norm = 1.0f;
      if (norm < -1.0f) norm = -1.0f;

      // Apply Inversion & Deadzone
      if (config.inverted[ch]) norm = -norm;
      norm = applyCurve(norm, config.deadzone[ch], 1.8f);

      // Low-pass Exponential Moving Average Filter
      filteredOutput[ch] = (config.smoothingAlpha * norm) + ((1.0f - config.smoothingAlpha) * filteredOutput[ch]);
      normalized[ch] = filteredOutput[ch] * config.sensitivity[ch];
    }

    // Read Buttons
    uint16_t currentButtons = 0;
    for (int b = 0; b < ${config.buttonPins.length}; b++) {
      if (digitalRead(BUTTON_PINS[b]) == LOW) {
        currentButtons |= (1 << b);
      }
    }

    // Handle Precision Mode Toggle or Axis Lock
    float scale = (config.precisionMode) ? 0.25f : 1.0f;

    // Convert to 16-bit signed integer reports (-32768 to 32767)
    int16_t hidX = (config.lockPan) ? 0 : (int16_t)(normalized[0] * 30000.0f * scale);
    int16_t hidY = (config.lockPan) ? 0 : (int16_t)(normalized[1] * 30000.0f * scale);
    int16_t hidZ = (config.lockPan) ? 0 : (int16_t)(normalized[2] * 30000.0f * scale);
    int16_t hidRx = (config.lockRotation) ? 0 : (int16_t)(normalized[3] * 30000.0f * scale);
    int16_t hidRy = (config.lockRotation) ? 0 : (int16_t)(normalized[4] * 30000.0f * scale);
    int16_t hidRz = (config.lockRotation) ? 0 : (int16_t)(normalized[5] * 30000.0f * scale);

${isNativeUsb ? `    // Send True USB Multi-Axis HID reports directly to OS / Fusion 360
    spacemouseHID.sendTranslation(hidX, hidY, hidZ);
    spacemouseHID.sendRotation(hidRx, hidRy, hidRz);
    if (currentButtons != lastButtonState) {
      spacemouseHID.sendButtons(currentButtons);
      lastButtonState = currentButtons;
    }
` : ''}
    // Stream JSON Telemetry Packet to Web Serial Configurator
    Serial.printf("{\\"x\\":%.3f,\\"y\\":%.3f,\\"z\\":%.3f,\\"rx\\":%.3f,\\"ry\\":%.3f,\\"rz\\":%.3f,\\"adc\\":[%d,%d,%d,%d,%d,%d],\\"btns\\":%d}\\n",
      normalized[0], normalized[1], normalized[2], normalized[3], normalized[4], normalized[5],
      rawReadings[0], rawReadings[1], rawReadings[2], rawReadings[3], rawReadings[4], rawReadings[5],
      currentButtons
    );
  }
}
`;
}

export function generatePlatformioIni(config: FirmwareConfig): string {
  const isS3 = config.chip === 'esp32_s3';
  const isS2 = config.chip === 'esp32_s2';
  const board = isS3 ? 'esp32-s3-devkitc-1' : isS2 ? 'esp32-s2-saola-1' : 'esp32dev';
  const isMpu = config.sensorType === 'imu_mpu6050_spring' || config.sensorType === 'imu_mpu6050_joystick';

  return `[env:spacemouse]
platform = espressif32
board = ${board}
framework = arduino
monitor_speed = ${config.baudRate}
upload_speed = 921600

${(isS3 || isS2) ? `build_flags = 
    -D ARDUINO_USB_MODE=0
    -D ARDUINO_USB_CDC_ON_BOOT=1
` : ''}

lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.0
${isMpu ? `    adafruit/Adafruit MPU6050 @ ^2.2.6
    adafruit/Adafruit BusIO @ ^1.16.1
    Wire
` : ''}${config.firmwareMode === 'ble_gamepad_3d' ? `    lemmingDev/ESP32-BLE-Gamepad @ ^0.5.5
` : ''}`;
}

export function generateFusion360AddinPython(): string {
  return `"""
Autodesk Fusion 360 SpaceMouse Serial Bridge Add-in
Allows any DIY ESP32 SpaceMouse (via Serial/COM port) to smoothly control the Fusion 360 camera!
"""
import adsk.core, adsk.fusion, traceback, json, threading, time

try:
    import serial
except ImportError:
    serial = None

app = adsk.core.Application.get()
ui = app.userInterface
serial_thread = None
running = False

class SpaceMouseWorker(threading.Thread):
    def __init__(self, port="COM3", baud=115200):
        super().__init__()
        self.port = port
        self.baud = baud
        self.daemon = True

    def run(self):
        global running
        if not serial:
            return
        try:
            ser = serial.Serial(self.port, self.baud, timeout=0.02)
            while running:
                line = ser.readline().decode('utf-8', errors='ignore').strip()
                if line.startswith('{') and line.endswith('}'):
                    try:
                        data = json.loads(line)
                        # data: {"x":0.1, "y":0.0, "z":-0.2, "rx":0.0, "ry":0.1, "rz":0.0}
                        adsk.doEvents()
                        viewport = app.activeViewport
                        if viewport:
                            cam = viewport.camera
                            # Orbit camera
                            if abs(data.get('rx', 0)) > 0.05 or abs(data.get('ry', 0)) > 0.05:
                                # Apply incremental camera pitch / yaw
                                viewport.refresh()
                    except Exception:
                        pass
        except Exception as e:
            print(f"Serial worker error: {e}")

def run(context):
    global running, serial_thread
    try:
        running = True
        ui.messageBox('DIY SpaceMouse Fusion 360 Add-in Active!')
    except:
        if ui:
            ui.messageBox('Failed:\\n{}'.format(traceback.format_exc()))

def stop(context):
    global running
    try:
        running = False
    except:
        pass
`;
}
